name: demo_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  http: ^1.2.0
  path: ^1.8.3
  process: ^5.0.2
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
